name: aha_table
version: 0.0.1
author: Luis Vargas <luisvargastijerino@gmail.com>
description: A Polymer element for a searchable, sortable, paginatable, inline-editable, selectable, copyable, removable, movable table/grid.
homepage: https://github.com/luisvt/aha_table_dart
environment:
  sdk: '>=1.6.0'
dependencies:
  polymer: '>=0.15.0 <0.16.0'
transformers:
- polymer:
    entry_points: examples/index.html
