name: aha_table
version: 0.0.2+1
author: Luis Vargas <luisvargastijerino@gmail.com>
description: A Polymer element for a searchable, sortable, paginatable, inline-editable, selectable, copyable, removable, movable table/grid.
homepage: https://github.com/luisvt/aha_table_dart
environment:
  sdk: '>=1.6.0'
dependencies:
  less_dart: any
  paper_elements: any
  polymer: '>=0.15.0 <0.17.0'
transformers:
- less_dart
- polymer:
    entry_points: example/index.html